all:
	cd ogg && make
	cd vorbis && make
	cd vorbisenc && make
	cd vorbisfile && make
    
clean:
	cd ogg && make
	cd vorbis && make clean
	cd vorbisenc && make clean
	cd vorbisfile && make clean